version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - dev-integracao-servicos_default

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - dev-integracao-servicos_default

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    container_name: logstash
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/mysql-connector-java-8.0.26.jar:/usr/share/logstash/mysql-connector-java-8.0.26.jar
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - dev-integracao-servicos_default
      
  jdbc-plugin:
    image: docker.elastic.co/logstash/logstash:7.12.0
    container_name: jdbc-plugin
    command: logstash-plugin install logstash-input-jdbc
    volumes:
      - ./config/mysql-connector-java-8.0.26.jar:/usr/share/logstash/mysql-connector-java-8.0.26.jar
    networks:
      - dev-integracao-servicos_default

networks:
  dev-integracao-servicos_default:
    external: true